name: Rust Unit Tests

on: [push, pull_request]

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo2junit
        run: cargo install cargo2junit

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit

#     disabled, generates too many errors
#      - name: Run Clippy
#        uses: clechasseur/rs-clippy-check@v3
#        with:
#          args: --all-features

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format json --report-time | tee results.json

      - name: Convert to JUnit
        run: cat results.json | cargo2junit > results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: results.xml

      - name: Set badge color
        shell: bash
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac

      - name: Create badge
        uses: emibcn/badge-action@v2.0.3
        with:
          label: Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: badge.svg

      - name: Upload badge to Gist
        # Upload only for nchain branch
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'nchain' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/nchain'
        uses: andymckay/append-gist-action@0.2
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/Danconnolly/ba7b66a3f55b19ca69abe8b8b537ae56
          file: badge.svg